### PR TITLE
Fix/#add readme

### PR DESCRIPTION
**Pull request by mdrianislam0or1**
Issue Title:  Add more information to the README - reporting #112 

Edit Readme file.

reporting

### CODE REVIEW

**Comment by Israel-Laguan** [comment]
Please try to mimick another repo, for example https://github.com/Israel-Laguan/Restaurant-Page

I suppose some needed stuff (other is optional)

- some kind of header like this:

```markdown
<!-- PROJECT SHIELDS -->
[![Forks][forks-shield]][forks-url]
[![Stargazers][stars-shield]][stars-url]
[![Issues-open][issues-open-shield]][issues-url]
[![Issues-closed][issues-closed-shield]][issues-url]
[![Contributors][contributors-shield]][contributors-url]
[![contributions welcome][contributions-welcome]][issues-url]

<!-- PROJECT LOGO -->
<br />
<p align="center">
  <a href="https://link here">
    <img src="some image here" alt="Logo" height="80">
  </a>

  <h1 align="center">
      title here
  </h1>

  <p align="center">
    Description HERE
    <br />
    🐞
    <a href="https://github.com/Israel-Laguan/repo name/issues">Report a Bug</a>
    🙋‍♂️
    <a href="https://github.com/Israel-Laguan/repo name/issues">Request Feature</a>
  </p>
</p>

```

**Comment by mdrianislam0or1** [comment]
The Url is not working : [etl-reporting.now.sh](https://etl-reporting.now.sh/)

**Comment by Israel-Laguan** [comment]
> The Url is not working : [etl-reporting.now.sh](https://etl-reporting.now.sh/)

Yeah, it can be erased, later we add other deployment link

**Comment by mdrianislam0or1** [comment]
Is it Ok now?

fix

**Review by Israel-Laguan — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Review by angelik0828 — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
With latest changes this is not working
image

**Review by Israel-Laguan — APPROVED** [review]

**Pull request merged**
